### ISSUE TITLE
Not yet published on npm?

### ISSUE THREAD

**Issue by mikestopcontinues** [prichodko/window-scroll-position#3]
Hey, is this not production ready? I tried to install on npm, and no dice.

```
npm ERR! code E404
npm ERR! 404 Not Found: @rehooks/window-scroll-position@latest
```

**Comment by corysimmons** [comment]
@prichodko @Andarist @jamiebuilds 

`@rehooks` isn't an org on npm: https://docs.npmjs.com/creating-an-org

Happy to publish all this rehooks stuff if someone wants to add me to GH org.

@mikestopcontinues tmp fix is `yarn add https://github.com/rehooks/window-scroll-position` I can't imagine this lib having many breaking changes.

---

Doesn't work anyway. 😂

**Comment by mikestopcontinues** [comment]
Thanks @corysimmons. I ended up just rolling my own. I think I've gotten hooked on writing hooks. ;)

**Comment by alexpricedev** [comment]
You can also just install via git repo: `npm i --save rehooks/window-scroll-position`

**Comment by corysimmons** [comment]
@remotealex downside to adding just the repo is you don't get [semver](https://semver.org/) "guarantees" and anytime someone `git clone; npm i` your project, they're going to get whatever is in `master` at that point in time.

Thus publishing to npm would be ideal.

**Comment by alexpricedev** [comment]
💯 agree, just a work around ;)

**Comment by veksen** [comment]
Might want to update the README :)

**Comment by garretteklof** [comment]
Might want to update the README to drop the '@': `yarn add rehooks/window-scroll-position` 🙂

**Comment by jamiebuilds** [comment]
published, sorry about that
